---
# This is a sample configuration of Open CAS deployment configuration

opencas_install_source: "rpm"
opencas_lvm_support: true

# List of all cache devices configuration
opencas_cache_devices:
  - cache_device: /dev/1-11       # path to device or partition
    id: 1                            # id used to corelate cores with cache instances
    cache_mode: wb                  # caching mode <wt, wb, wa, pt, wo>
    force: true                   # [OPTIONAL] Ignore and overwrite existing partition table
    cleaning_policy: alru            # [OPTIONAL] cleaning policy <alru, acp, nop>
    promotion_policy: always         # [OPTIONAL] cleaning policy <always, nhit>
    line_size: 4                     # [OPTIONAL] cache line size <4, 8, 16, 32, 64> [kb]
    io_class: default.csv            # [OPTIONAL] io classification file name
                                     # all files used here should be put in
                                     # roles/opencas-deploy/files/
  - cache_device: /dev/1-15       # path to device or partition
    id: 2                            # id used to corelate cores with cache instances
    cache_mode: wb                  # caching mode <wt, wb, wa, pt, wo>
    force: true                   # [OPTIONAL] Ignore and overwrite existing partition table
    cleaning_policy: alru            # [OPTIONAL] cleaning policy <alru, acp, nop>
    promotion_policy: always         # [OPTIONAL] cleaning policy <always, nhit>
    line_size: 4                     # [OPTIONAL] cache line size <4, 8, 16, 32, 64> [kb]
    io_class: default.csv

# List of all cached volumes
opencas_cached_volumes:
    - id: 1                    # id of core device
      cache_id: 1              # id of cache defined in open_cas_cache_devices list
      cached_volume: /dev/1-1  # path to cached device or partition
    - id: 2
      cache_id: 2
      cached_volume: /dev/1-2
...
