---
- hosts: opencas_nodes
  tasks:
    - name: Enable lvm support for cas devices
      lineinfile:
        path: /etc/lvm/lvm.conf
        insertafter: '# types = \[ "fd", 16 ]'
        line: 'types = [ "cas", 16 ]'
      when: opencas_lvm_support | bool
      become: True
...
