---
- name: Check if Open CAS configuration for host group is defined
  fail:
    msg: "Couldn't find configuration for Open CAS devices. Did you configure group/host_vars?"
  when: (opencas_cache_devices is not defined) or (opencas_cached_volumes is not defined)

- name: Copy io classes configuration files
  include: copy-ioclass-config.yml
  become: True

- name: Validate CAS config
  include: validate-config.yml

- name: Configure devices
  include: configure-devices.yml
  become: True
...
