---
- name: Clone and checkout Open CAS repository
  git:
    repo: "{{ opencas_repo_url }}"
    dest: "{{ opencas_path }}"
    version: "{{ opencas_version }}"
  when: not opencas_installed or opencas_installed_version != opencas_version
  become: True

- name: Configure Open CAS
  shell: ./configure
  args:
    chdir: "{{ opencas_path }}"
  become: True

- name: Compile Open CAS
  make:
    chdir: "{{ opencas_path }}"
  when: not opencas_installed or opencas_installed_version != opencas_version
  become: True

- name: Install Open CAS
  make:
    chdir: "{{ opencas_path }}"
    target: install
  when: not opencas_installed or opencas_installed_version != opencas_version
  become: True

- name: Update facts
  cas:
    gather_facts: True
  become: True
...
