---
- name: Check if installation may proceed
  fail:
    msg: |
      "Open CAS is currently installed in version
      {{ opencas_installed_version['CAS Cache Kernel Module'] }} and has devices
      configured. Please change your opencas_version variable (currently: {{ opencas_version }})
      and re-run or use teardown and rebuild the configuration."
  when: (opencas_installed and
          ((opencas_installed_version != opencas_version) and opencas_devices_started))

- include: "{{ opencas_install_source }}-install.yml"
  when: '{{ ansible_distribution_major_version }} == "CentOS"'
