---
- name: 45Drives Repository - Configure 45drives repository
  yum_repository:
    name: 45drives
    description: 45Drives $basearch repo
    gpgcheck: no
    enabled: yes
    state: present
    baseurl: "http://images.45drives.com/ceph/rpm/el{{ ansible_distribution_major_version }}"
    file: 45drives
    priority: "1"
  register: result
  until: result is success

- name: Install open-cas-linux
  block:
    - name: Remove kernel-debug-devel if installed
      package:
        name: kernel-debug-devel
        state: absent
      register: result
      until: result is succeeded

    - name: Install kernel-devel
      package:
        name: kernel-devel
        state: present
      register: result
      until: result is succeeded      

    - name: install open-cas-linux and modules
      package:
        name: open-cas-linux
        state: latest
      register: result
      until: result is succeeded

    - name: Load open-cas kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      with_items:
        - cas_disk
        - cas_cache
